// <auto-generated />
using System;
using E9U.Tangello.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E9U.Tangello.Data.Migrations.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20200601185804_InUseProjectNames")]
    partial class InUseProjectNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E9U.Tangello.Data.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasAlternateKey("Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("E9U.Tangello.Data.Entities.CategoryToProjectTypeMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("ProjectTypeID");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ProjectTypeID");

                    b.ToTable("CategoryToProjectTypeMappings");
                });

            modelBuilder.Entity("E9U.Tangello.Data.Entities.InUseProjectName", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectDescription")
                        .HasMaxLength(2000);

                    b.Property<int>("ProjectNameID");

                    b.HasKey("ID");

                    b.HasIndex("ProjectNameID");

                    b.ToTable("InUseProjectNames");
                });

            modelBuilder.Entity("E9U.Tangello.Data.Entities.ProjectName", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasAlternateKey("Name");

                    b.ToTable("ProjectNames");
                });

            modelBuilder.Entity("E9U.Tangello.Data.Entities.ProjectNameToCategoryMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("ProjectNameID");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ProjectNameID");

                    b.ToTable("ProjectNameToCategoryMappings");
                });

            modelBuilder.Entity("E9U.Tangello.Data.Entities.ProjectType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasAlternateKey("Name");

                    b.ToTable("ProjectTypes");
                });

            modelBuilder.Entity("E9U.Tangello.Data.Entities.CategoryToProjectTypeMapping", b =>
                {
                    b.HasOne("E9U.Tangello.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("E9U.Tangello.Data.Entities.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("E9U.Tangello.Data.Entities.InUseProjectName", b =>
                {
                    b.HasOne("E9U.Tangello.Data.Entities.ProjectName", "ProjectName")
                        .WithMany()
                        .HasForeignKey("ProjectNameID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("E9U.Tangello.Data.Entities.ProjectNameToCategoryMapping", b =>
                {
                    b.HasOne("E9U.Tangello.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("E9U.Tangello.Data.Entities.ProjectName", "ProjectName")
                        .WithMany()
                        .HasForeignKey("ProjectNameID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
